project_id = "gvrabsrytextpwaxxwnf"

[functions.generate-meme-image]
verify_jwt = false

[functions.generate-meme-caption]
verify_jwt = false

[functions.get-trending-topics]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false